# Generated by Django 2.1.5 on 2019-01-20 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ARQC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ATC', models.CharField(max_length=4)),
                ('TSI', models.CharField(max_length=4)),
                ('TVR', models.CharField(max_length=10)),
                ('AID', models.CharField(max_length=16)),
                ('app_label', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('no', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('exp_date', models.DateField(verbose_name='Exp Date')),
            ],
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('batch_no', models.CharField(max_length=6)),
                ('trace_no', models.CharField(max_length=6)),
                ('date', models.DateTimeField(verbose_name='date-time')),
                ('ref_no', models.CharField(max_length=12)),
                ('app_code', models.CharField(max_length=6)),
                ('base', models.FloatField()),
                ('tips', models.FloatField()),
                ('signature_img', models.ImageField(upload_to='media/imgs/signatures')),
                ('receiptPDF', models.FileField(upload_to='media/PDFs')),
                ('arqc', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.ARQC')),
                ('card', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Card')),
                ('merchant', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Merchant')),
                ('terminal', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Terminal')),
            ],
        ),
    ]
