# Generated by Django 2.1.5 on 2019-01-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='receiptPDF',
            field=models.FileField(upload_to='PDFs'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='signature_img',
            field=models.ImageField(upload_to='imgs/signatures'),
        ),
    ]
