# Generated by Django 2.1.5 on 2019-01-19 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='signature_img',
            field=models.ImageField(upload_to='media/imgs/signatures'),
        ),
    ]
