# Generated by Django 2.1.5 on 2019-01-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190119_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='receiptPDF',
            field=models.FileField(default=1, upload_to='media/PDFs'),
            preserve_default=False,
        ),
    ]
