# Generated by Django 2.1.5 on 2019-01-19 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_transaction_receiptpdf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='exp_date',
            new_name='date',
        ),
    ]
